#ifndef LIB_H
#define LIB_H

#ifdef MYUNITYPLUGIN_EXPORT
#define MYUNITYPLUGIN_SYMBOL __declspec(dllexport)
#else // !MYUNITYPLUGIN_EXPORT
//SECOND LAYER BEGIN
#ifdef MYUNITYPLUGIN_IMPORT
#define MYUNITYPLUGIN_SYMBOL __declspec(dllimport)
#else // !MYUNITYPLUGIN_IMPORT
//THIRD LAYER BEGIN
#ifdef MYUNITYPLUGIN_SYMBOL
#define MYUNITYPLUGIN_SYMBOL
#endif // MYUNITYPLUGIN_EXPORT
//THIRD LAYER END
#endif // MYUNITYPLUGIN_IMPORT
//SECOND LAYER END
#endif // MYUNITYPLUGIN_EXPORT


#endif // !LIB_H
